"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, CaretDown, CheckCircle, Copy, DotsThree, DownloadSimple, FileText, GearSix, GridFour, MagnifyingGlass, Plus, Trash, UserCircle, UsersThree } from "@phosphor-icons/react";
type Item = { id:number; description:string; rate:number; qty:number };
const money = new Intl.NumberFormat("en-US", { style:"currency", currency:"USD" });
export default function Home() {
 const [items,setItems]=useState<Item[]>([{id:1,description:"Brand strategy workshop",rate:1200,qty:1},{id:2,description:"Visual identity direction",rate:1800,qty:1},{id:3,description:"Website design · 4 pages",rate:450,qty:4}]);
 const [sent,setSent]=useState(false); const [client,setClient]=useState("Mira Chen");
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.rate*i.qty,0),[items]); const tax=subtotal*.08; const total=subtotal+tax;
 const update=(id:number,key:keyof Item,value:string|number)=>setItems(rows=>rows.map(i=>i.id===id?{...i,[key]:value}:i));
 return <main className="shell"><aside className="sidebar"><div className="mark">b</div><nav><button className="nav-item active" aria-label="Invoices"><FileText size={21} weight="bold"/></button><button className="nav-item" aria-label="Dashboard"><GridFour size={21}/></button><button className="nav-item" aria-label="Clients"><UsersThree size={21}/></button><button className="nav-item" aria-label="Settings"><GearSix size={21}/></button></nav><button className="avatar">JD</button></aside><section className="workspace">
 <header className="topbar"><button className="back"><ArrowLeft size={18}/> Invoices</button><div className="top-actions"><button className="icon-button" aria-label="Search"><MagnifyingGlass size={20}/></button><button className="icon-button" aria-label="More options"><DotsThree size={22} weight="bold"/></button><button className="profile"><span className="mini-avatar">JD</span><span>Jordan Davis</span><CaretDown size={14}/></button></div></header>
 <div className="content"><section className="editor"><div className="page-title"><div><p className="eyebrow">DRAFT INVOICE</p><h1>New invoice</h1></div><span className="saved"><CheckCircle size={17} weight="fill"/> Saved just now</span></div>
 <div className="fields-row"><label className="field"><span>Bill to</span><div className="input-with-icon"><UserCircle size={20}/><input value={client} onChange={e=>setClient(e.target.value)}/><CaretDown size={15}/></div><small>mira@atelier.com</small></label><label className="field compact"><span>Invoice number</span><input value="INV-2024-028" readOnly/></label><label className="field compact"><span>Due date</span><input value="Jun 28, 2024" readOnly/></label></div>
 <div className="line-items"><div className="table-head"><span>ITEM</span><span>RATE</span><span>QTY</span><span>AMOUNT</span><span/></div>{items.map(i=><div className="line" key={i.id}><input className="description" value={i.description} onChange={e=>update(i.id,"description",e.target.value)}/><div className="money-input"><span>$</span><input type="number" value={i.rate} onChange={e=>update(i.id,"rate",Number(e.target.value))}/></div><input className="qty" type="number" min="1" value={i.qty} onChange={e=>update(i.id,"qty",Number(e.target.value))}/><strong>{money.format(i.rate*i.qty)}</strong><button onClick={()=>setItems(rows=>rows.filter(x=>x.id!==i.id))} className="delete" aria-label="Remove item"><Trash size={17}/></button></div>)}<button className="add-item" onClick={()=>setItems(rows=>[...rows,{id:Date.now(),description:"New service",rate:0,qty:1}])}><Plus size={17} weight="bold"/> Add line item</button></div>
 <div className="notes-area"><label>Notes</label><textarea defaultValue="Thank you for working with us. Payment is due within 14 days."/></div></section>
 <aside className="summary"><div className="summary-header"><span>INVOICE TOTAL</span><button aria-label="Copy invoice link"><Copy size={17}/></button></div><div className="total">{money.format(total)}</div><div className="breakdown"><div><span>Subtotal</span><span>{money.format(subtotal)}</span></div><div><span>Tax <em>8%</em></span><span>{money.format(tax)}</span></div><div className="total-row"><span>Total</span><strong>{money.format(total)}</strong></div></div><div className="payment-card"><div className="card-icon">✦</div><div><strong>Get paid faster</strong><p>Add a payment link to this invoice.</p></div><button>Add</button></div><button className="send" onClick={()=>setSent(true)}>{sent?<><CheckCircle size={19} weight="fill"/> Invoice sent</>:"Send invoice"}</button><button className="download"><DownloadSimple size={19}/> Download PDF</button><p className="help">Your client will receive a clean, secure payment link.</p></aside></div></section></main>;
}
